language: node_js
cache: yarn
addons:
  apt:
    packages:
      - docker-ce
services:
  - docker
deploy:
  on: master
  provider: script
  script:
    - docker build -t cw-nasa .;
    - echo "$DOCKER_PASSWORD" | docker login --username="$DOCKER_USERNAME" --password-stdin registry.heroku.com;
    - docker tag cw-nasa registry.heroku.com/cw-nasa/web;
    - docker push registry.heroku.com/cw-nasa/web;
